# Generated by Django 4.2.2 on 2023-06-12 22:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticQuestionnaireSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire_type', models.TextField()),
                ('patient_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticQuestionnaireSubmissionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.IntegerField()),
                ('questionnaire_type', models.TextField()),
                ('symptom', models.TextField()),
                ('item_string', models.TextField()),
                ('item_index', models.IntegerField()),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('score_increments', models.IntegerField()),
                ('patient_score', models.IntegerField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow_api.diagnosticquestionnairesubmission')),
            ],
        ),
    ]
