# Generated by Django 4.2.2 on 2023-06-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_name', models.CharField(choices=[('Madrs-s', 'Madrs-s'), ('Madrs', 'Madrs'), ('Phq-9', 'Phq-9')], default='Madrs', max_length=7)),
            ],
        ),
    ]
